In this notebook we're going to cover some of the most fundamental concepts of tensors using tensorflow.
* introduction to tenosrs.
* Manipulating tensors
* tensor and numpy
* using @tf.function (a way to speed up your regular python function)
* uisng gpus with tensor flow
* Exercise try your self

## Introduction to tensors

In [68]:
import tensorflow as tf
print(tf.__version__)

2.12.0


In [69]:
scaler = tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [70]:
scaler.ndim

0

## Creating tensors with variable keyword

In [71]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [72]:
changeable_tensor = tf.Variable([10,7])
unchangable_tensor = tf.constant([10,7])

In [73]:
changeable_tensor,unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [74]:
## changeable_tensor[0] = 7

In [75]:
changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

## Creating random tensors
Random tensors are tensors of some arbitrary size which contain random numbers.

In [76]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

## Shuffle order of tensor


In [77]:
not_shuffled = tf.constant ([[10,7],
                             [3,4],
                             [2,5]])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [78]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

## Other ways to make tensors

In [79]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [80]:
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

## Turn Numpy arryas into the tensors

The main difference between NumPy arrays and tensorFlow tensors is that tensors can be run on a GPU computing more efficiently.

In [81]:
import numpy as np

numpy_a = np.arange(1,25 , dtype = np.int32)
numpy_a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [82]:
b =tf.constant(numpy_a,shape=(2,3,4))

In [83]:
b.ndim



3

## Getting information from the tensors 
* Shape 
* Rank
* Axis or dimension
* Size


In [84]:
rank_4 = tf.zeros(shape=[2,3,4,5])
rank_4

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [85]:
rank_4.shape ,rank_4.ndim , tf.size(rank_4)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [86]:
print(tf.size(rank_4).numpy())

120


In [87]:
rank_4[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [88]:
rank_4[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [89]:
rank_2 = tf.constant([[10,7],
                     [3,4]])

In [90]:
rank_3 = rank_2[...,tf.newaxis]


In [91]:
tf.expand_dims(rank_2 ,axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

## Manipulating tesnor 
This includes adding and subtracting or multiplying and dividing the tensors.
Matrix multiplication is very common multiplication used in machine learning models.

In [92]:
tensor = tf.constant([[10,7],[2,3]])

In [93]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  3]], dtype=int32)>

In [94]:
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [12, 13]], dtype=int32)>

In [95]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 20,  30]], dtype=int32)>

In [96]:
# Matrix multiplication in tensorflow

print(tensor)
tf.matmul(tensor , tensor)

tf.Tensor(
[[10  7]
 [ 2  3]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[114,  91],
       [ 26,  23]], dtype=int32)>

In [97]:
tensor.shape

TensorShape([2, 2])

In [98]:
x = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
y  = tf.constant([[7,8],
                  [9,10]])

In [99]:
x , y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10]], dtype=int32)>)

In [100]:
## x * y

In [101]:
tf.matmul(x,y)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 25,  28],
       [ 57,  64],
       [ 89, 100]], dtype=int32)>

In [102]:
x = tf.reshape(x,shape=[2,3])

In [103]:
x


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

## Changing data type to tensors

In [104]:
# create a tensor with new data type
B = tf.constant([[10,7],
                 [8,9.]])

In [105]:

B

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[10.,  7.],
       [ 8.,  9.]], dtype=float32)>

In [106]:
c  = tf.constant([7,10])
c.dtype

tf.int32

In [107]:
D = tf.cast(B , dtype = tf.float16)
D , D.dtype

(<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
 array([[10.,  7.],
        [ 8.,  9.]], dtype=float16)>,
 tf.float16)

## Aggregating the tensors

It means condensing them from multiple values down to a smaller amount of values.


In [108]:
# Get the absiolute value
d = tf.constant([-7,-10])
d

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [109]:
tf.abs(d)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

### Let's go through the following forms of aggregation:

* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [111]:
# Create a random tensor with values between 0 and 100 of size 50

e = tf.constant(np.random.randint(0,100,size = 50))
e

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([10, 48, 35, 81, 14,  7, 39,  0, 15, 94, 37, 30, 43, 38, 17, 54, 57,
       51,  7, 68,  9, 59, 45,  3, 78, 26,  7, 36, 65, 46, 87, 41, 90,  7,
       70,  7, 29, 88, 86,  7, 26, 75, 36, 60, 20, 65, 57, 47,  3, 16])>

In [112]:
tf.size(e) , tf.shape , e.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>,
 <function tensorflow.python.ops.array_ops.shape_v2(input, out_type=tf.int32, name=None)>,
 1)

In [113]:
tf.reduce_min(e)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [114]:
tf.reduce_max(e)

<tf.Tensor: shape=(), dtype=int64, numpy=94>

In [116]:
tf.reduce_mean(e)

tf.Tensor(40, shape=(), dtype=int64)


In [117]:
tf.reduce_sum(e)

<tf.Tensor: shape=(), dtype=int64, numpy=2036>

In [122]:
import tensorflow_probability as tfp

tfp.stats.variance(e)

<tf.Tensor: shape=(), dtype=int64, numpy=747>

In [123]:
tf.math.reduce_std(tf.cast(e, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=27.337183>

## Find the positional maximum and minimum

In [124]:
tf.random.set_seed(42)

f = tf.random.uniform(shape=[50])
f

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [125]:
tf.argmax(f)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [126]:
f[tf.argmax(f)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [128]:
tf.argmin(f)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [129]:
f[tf.argmin(f)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [130]:
tf.random.set_seed(42)

g = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
g

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [131]:
g.shape

TensorShape([1, 1, 1, 1, 50])

In [132]:
g_squeezed = tf.squeeze(g)
g_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [133]:
g_squeezed.shape

TensorShape([50])

### One hot encoding


In [139]:
some_list=[0,1,2]

tf.one_hot(some_list, depth=3, on_value = 5 , off_value = 10)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 5, 10, 10],
       [10,  5, 10],
       [10, 10,  5]], dtype=int32)>

### Squaring , log and squarerrot

In [140]:
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [141]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [144]:
tf.math.sqrt(tf.cast(H, dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

### Tensors and numpy

Tensorflow interacts directly from numpy array

In [146]:
j = tf.constant(np.array([3,7,10]))

In [147]:
type(np.array(j))

numpy.ndarray

In [148]:
j

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([ 3,  7, 10])>

numpy creates float64 data type
tf.constant creates tensor float32 data type